---
tenants:
  - name: ESG_Ch2_Ex02

    application_profiles:
      - name: security-zones
        endpoint_security_groups:
          - name: subnet-group-01
            vrf: vrf-01
            epg_selectors:
              - application_profile: network-segments
                endpoint_group: VLAN10
              - application_profile: network-segments
                endpoint_group: VLAN20
          - name: subnet-group-02
            vrf: vrf-01
            epg_selectors:
              - application_profile: network-segments
                endpoint_group: VLAN30
              - application_profile: network-segments
                endpoint_group: VLAN40

      - name: network-segments
        endpoint_groups:
          - name: VLAN10
            bridge_domain: 10.0.1.0_24
            vmware_vmm_domains:
              - name: ESG_vmmdom
                u_segmentation: false
                deployment_immediacy: immediate
                resolution_immediacy: immediate
            physical_domains:
              - name: ESG_phydom
            static_ports:
              - {vlan_id: 10, pod_id: 1, node_id: 101, port_id: 1}
          - name: VLAN20
            bridge_domain: 10.0.2.0_24
            vmware_vmm_domains:
              - name: ESG_vmmdom
                u_segmentation: false
                deployment_immediacy: immediate
                resolution_immediacy: immediate
            physical_domains:
              - name: ESG_phydom
            static_ports:
              - {vlan_id: 20, pod_id: 1, node_id: 101, port_id: 1}
          - name: VLAN30
            bridge_domain: 10.0.3.0_24
            physical_domains:
              - name: ESG_phydom
            static_ports:
              - {vlan_id: 30, pod_id: 1, node_id: 101, port_id: 1}
          - name: VLAN40
            bridge_domain: 10.0.4.0_24
            physical_domains:
              - name: ESG_phydom
            static_ports:
              - {vlan_id: 40, pod_id: 1, node_id: 101, port_id: 1}

    vrfs:
      - name: vrf-01

    bridge_domains:
      - name: 10.0.1.0_24
        vrf: vrf-01
        subnets:
          - ip: 10.0.1.1/24
            scope:
              - private
      - name: 10.0.2.0_24
        vrf: vrf-01
        subnets:
          - ip: 10.0.2.1/24
            scope:
              - private
      - name: 10.0.3.0_24
        vrf: vrf-01
        subnets:
          - ip: 10.0.3.1/24
            scope:
              - private
      - name: 10.0.4.0_24
        vrf: vrf-01
        subnets:
          - ip: 10.0.4.1/24
            scope:
              - private
