---
tenants:
  - name: ESG_Ch2_Ex09

    application_profiles:
      - name: security-zones
        endpoint_security_groups:
          - name: application-01
            vrf: vrf-01
            ip_subnet_selectors:
              - ip: 10.0.1.0/25
              - ip: 10.0.2.0/25
              - ip: 10.0.3.0/25
              - ip: 10.0.4.0/25
          - name: application-02
            vrf: vrf-01
            ip_subnet_selectors:
              - ip: 10.0.1.128/25
              - ip: 10.0.2.128/25
              - ip: 10.0.3.128/25
              - ip: 10.0.4.128/25

      - name: network-segments
        endpoint_groups:
          - name: VLAN10_11
            bridge_domain: 10.0.1.0_24
            vmware_vmm_domains:
              - name: ESG_vmmdom
                u_segmentation: true
                deployment_immediacy: immediate
                resolution_immediacy: immediate
          - name: VLAN20_21
            bridge_domain: 10.0.2.0_24
            vmware_vmm_domains:
              - name: ESG_vmmdom
                u_segmentation: true
                deployment_immediacy: immediate
                resolution_immediacy: immediate
          - name: VLAN30
            bridge_domain: 10.0.3.0_24
            intra_epg_isolation: true
            proxy_arp: true
            physical_domains:
              - name: ESG_phydom
            static_ports:
              - vlan_id: 30
                pod_id: 1
                node_id: 101
                port_id: 1

    vrfs:
      - name: vrf-01

    bridge_domains:
      - name: 10.0.1.0_24
        vrf: vrf-01
        subnets:
          - ip: 10.0.1.1/24
            scope:
              - private
      - name: 10.0.2.0_24
        vrf: vrf-01
        subnets:
          - ip: 10.0.2.1/24
            scope:
              - private
      - name: 10.0.3.0_24
        vrf: vrf-01
        subnets:
          - ip: 10.0.3.1/24
            scope:
              - private
